Error Message when VideoCapture1.py is run
Following files will be zipped:
C:/Users/Rastakib/Desktop/VideoCapture/Version3.66Python/VideoCaptured\18-09-16-17-32-48.avi
C:/Users/Rastakib/Desktop/VideoCapture/Version3.66Python/VideoCaptured\18-09-16-17-32-53.avi
C:/Users/Rastakib/Desktop/VideoCapture/Version3.66Python/VideoCaptured\18-09-16-17-32-58.avi
All files zipped successfully!
Email sent!
[ WARN:0] videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:0] videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
Following files will be zipped:
Traceback (most recent call last):
  File "VideoCapture1.py", line 37, in <module>
    zip_del()
  File "C:\Users\Rastakib\Desktop\VideoCapture\Version3.66Python\s7zarch.py", line 41, in main
    shutil.rmtree("C:/Users/Rastakib/Desktop/VideoCapture/Version3.66Python/VideoCaptured")
  File "C:\Users\Rastakib\Desktop\VideoCapture\Version3.66Python\env\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Rastakib\Desktop\VideoCapture\Version3.66Python\env\lib\shutil.py", line 376, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "C:\Users\Rastakib\Desktop\VideoCapture\Version3.66Python\env\lib\shutil.py", line 374, in _rmtree_unsafe
    names = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/Rastakib/Desktop/VideoCapture/Version3.66Python/VideoCaptured'